TUGAS SESI 2 

ALVITTO JUAN RAMADHAN - 20210801455

In [1]:
nama = "Alvitto Juan Ramadhan"
nim_mahasiswa = "20210801455"
mata_kuliah = "Machine Learning"

In [2]:
print("DATA DIRI")
print("Nama : ", nama)
print("NIM Mahasiswa: ", nim_mahasiswa)
print("Perkuliahan: ", mata_kuliah)

DATA DIRI
Nama :  Alvitto Juan Ramadhan
NIM Mahasiswa:  20210801455
Perkuliahan:  Machine Learning


In [1]:
matriksC= [[1,2,3],[4,5,6]]

In [2]:
print(matriksC)

[[1, 2, 3], [4, 5, 6]]


In [3]:
matriks = [[2,2],[2,2],[2,2]]

In [4]:
print(matriks)

[[2, 2], [2, 2], [2, 2]]


In [7]:
pip install numpy

  Obtaining dependency information for numpy from https://files.pythonhosted.org/packages/93/fd/3f826c6d15d3bdcf65b8031e4835c52b7d9c45add25efa2314b53850e1a2/numpy-1.26.0-cp311-cp311-win_amd64.whl.metadata
     ---------------------------------------- 0.0/61.1 kB ? eta -:--:--
     ------ --------------------------------- 10.2/61.1 kB ? eta -:--:--
     ------------ ------------------------- 20.5/61.1 kB 162.5 kB/s eta 0:00:01
     ------------------- ------------------ 30.7/61.1 kB 186.2 kB/s eta 0:00:01
     -------------------------------------- 61.1/61.1 kB 295.6 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.2/15.8 MB 3.1 MB/s eta 0:00:06
   - -------------------------------------- 0.5/15.8 MB 5.0 MB/s eta 0:00:04
   -- ------------------------------------- 0.8/15.8 MB 6.0 MB/s eta 0:00:03
   --- ------------------------------------ 1.2/15.8 MB 6.4 MB/s eta 0:00:03
   ---- ------------------------

In [8]:
import numpy as np

In [9]:
from numpy import *

In [10]:
matriks = range(32)
matriks = reshape(matriks, (4,8))

In [11]:
print(matriks)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]
 [24 25 26 27 28 29 30 31]]


In [12]:
import numpy as np
from numpy import *

In [13]:
matriks = np.random.randint(1,5,(3,30))

In [14]:
print(matriks)

[[1 2 3 2 1 3 4 2 1 1 1 4 4 2 4 4 4 2 3 1 3 2 4 2 4 2 1 3 3 3]
 [2 4 4 4 3 1 3 1 2 1 3 4 2 4 1 3 2 4 1 3 3 3 3 1 1 2 1 4 2 1]
 [1 2 1 4 4 3 3 1 2 4 2 3 1 1 1 3 4 4 2 2 4 2 3 3 2 4 2 1 4 4]]
